from tkinter import *
from tkinter import messagebox
# import test
def getInfo():
    FFMC = (float)(E1.get())
    DMC = (float)(E2.get())
    DC = (float)(E3.get())
    ISI = (float)(E4.get())
    temp = (float)(E5.get())
    RH = (float)(E6.get())
    wind = (float)(E7.get())
    test = []
    test.append(FFMC)
    test.append(DMC)
    test.append(DC)
    test.append(ISI)
    test.append(temp)
    test.append(RH)
    test.append(wind)
    return test
top = Tk(className='Cảnh báo cháy rừng')
top.minsize(width=300, height=500)
top.maxsize(width=300, height=500)
L1 = Label(top, text="FFMC")
L1.pack()
E1 =Entry(top, bd=5)
E1.pack()
L2 = Label(top, text="DMC")
L2.pack()
E2 =Entry(top, bd=5)
E2.pack()
L3 = Label(top, text="DC")
L3.pack()
E3 =Entry(top, bd=5)
E3.pack()
L4 = Label(top, text="ISI")
L4.pack()
E4 =Entry(top, bd=5)
E4.pack()
L5 = Label(top, text="temp")
L5.pack()
E5 =Entry(top, bd=5)
E5.pack()
L6 = Label(top, text="RH")
L6.pack()
E6 =Entry(top, bd=5)
E6.pack()
L7 = Label(top, text="wind")
L7.pack()
E7 =Entry(top, bd=5)
E7.pack()
B = Button(top, text="submit", command=getInfo)
B.pack()
close = Button(top, text='Close', command=top.destroy)
close.pack()
top.mainloop()



